# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Test with Maven
      run: | 
        ls -l
        cd thestarsaboveyou-automation
        mvn -B test
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Cucumber HTML Report
        path: thestarsaboveyou-automation/target/cucumber.html
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: TestNG Reports
        path: thestarsaboveyou-automation/target/surefire-reports
    
    - name: Publish TestNG Report
      if: always()
      uses: scacap/action-surefire-report@v1

  Release:
    runs-on: ubuntu-latest
    needs: Test
    steps:
    - name: Release it
      run: echo "Releasing ..."
